# Support StellarDripz development
github: [StellarDripz]
buy_me_a_coffee: stellardripz
custom: ["https://stellar.expert/explorer/testnet/contract/CDLZFC3SYJYDZT7K67VQ75BQHHPYXSOF3K5K5G3L6YP2MQUBQ7SJVMHV"]
